---
title: "Reproduzindo algumas tabelas do Relatório ABJ/NUPPS"
author: "Leopoldo Gutierre"
date: "14/08/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Cleaning the workspace
rm(list = ls())

# Loading the packages
library(tidyverse)
library(knitr)
library(abjutils)

#Path
mypath <- "/home/leopoldo/Dropbox/UBC_files/2019_S/Summer_Paper/abjCorrup_local/"
```

## Reproduzindo a tabela 28 do relatorio

O resultado que eu consegui foi o seguinte:

```{r, echo=FALSE}

# Loading the elections data
abj_reus_pol <- readRDS( paste0(mypath, "data/abj_reus_pol_1a_tjsp.rds"))
dnupps <- readRDS( paste0(mypath, "data/dnupps.rds"))

# Making the table of the report
aux <- abj_reus_pol$cargo
aux[is.na(abj_reus_pol$cargo)] = "NÃO POLÍTICO"
tab <- tabela(aux,label = "Cargo")
colnames(tab)[2] <- "Frequência"
kable(tab, row.names=FALSE)
```


## Contando o número de processos sem identificação de réu

```{r, echo=FALSE}
# Let's check the court proceeding without a defendant
dnupps <- dnupps %>% 
  filter(tribunal == "TJSP") %>% 
  arrange(n_processo)

# Note that we have several court proceeding without the name of the defendant
aux <- abj_reus_pol %>%
  distinct(n_processo) %>%
  arrange(n_processo) %>% 
  mutate(existdef = 1)

aux2 <- full_join(dnupps, aux, by="n_processo") 
aux2$existdef[is.na(aux2$existdef)] = 0
tab2 <- tabela(aux2$existdef,label = "Processo tem réu?")
colnames(tab2)[2] <- "Frequência"
kable(tab2, row.names=FALSE)
```
