classifica_tipo_movimentacao <- function(descricao){
  case_when(
    #str_detect(descricao, "autos com \\(conclusao\\) juiz|concluso para decisao|concluso para sentenca|concluso para despacho") ~ "Concluso",
    str_detect(descricao, regex("ato ordinario|ordinatorio", ignore_case = TRUE)) ~ "Ato Ordinario",
    str_detect(descricao, "autos com \\(conclusao\\) juiz para sentenca|(conclusos?|conclusao) para sentenca") ~ "Concluso para sentença", 
    str_detect(descricao, "autos com \\(conclusao\\) juiz para despacho/decisao|(conclusos?|conclusao) para despacho") ~ "Concluso para despacho", 
    str_detect(descricao, "(conclusos?|conclusao) para decisao") ~ "Concluso para decisão", 
    str_detect(descricao, "recebo a denuncia|recebida a denuncia|denuncia recebida|rejeitada a denuncia") ~ "Denúncia recebida",
    str_detect(descricao, "conclusos") ~ "Concluso",
    str_detect(descricao, "prescricao|(extincao da|extinta a) punibilidade|condenacao|absolvicao|procedente|sentenca") ~ "Sentença",
    str_detect(descricao, "despacho") ~ "Despacho",
    str_detect(descricao, "decisao") ~ "Decisão",
    str_detect(descricao, "recurso") ~ "Recurso",
    str_detect(descricao, "declinio de competencia") ~ "Declínio de competência",
    str_detect(descricao, "apensado") ~ "Apensado",
    str_detect(descricao, "processo arquivado|arquivamento|arquivado provisoriamente|suspenso|arquivado definitivamente") ~ "Arquivamento",
    str_detect(descricao, "ato cumprido") ~ "Cumprimento de ato",
    str_detect(descricao, "devolucao|recebido|recebimento|retorno") ~ "Recebimento",
    str_detect(descricao, regex("remessa externa", ignore_case = TRUE)) ~ "Remessa externa",
    str_detect(descricao, regex("vista|vista ao|remessa|remetido", ignore_case = TRUE)) ~ "Remessa",
    str_detect(descricao, regex("carga", ignore_case = TRUE)) ~ "Carga",
    str_detect(descricao, "audiencia") & str_detect(descricao, regex("designada")) ~ "Audiência Designada",
    str_detect(descricao, "audiencia") & str_detect(descricao, regex("nao realizada")) ~ "Audiência Não Realizada",
    str_detect(descricao, "audiencia") & str_detect(descricao, regex("(adiada|redesignada|redesigno)")) ~ "Audiência Adiada",
    str_detect(descricao, regex("audiencia convertida", ignore_case = TRUE)) ~ "Audiência Convertida em Diligência",
    str_detect(descricao, "audiencia") & str_detect(descricao, regex("prova de juiz|prova de acusacao|continuacao|especial|admonitoria|prova de defesa|juri|custodia|interrogatorio|julgamento|audiencia tipo |realizada|instrucao e julgamento")) ~ "Audiência Realizada",
    str_detect(descricao, "audiencia") ~ "Audiência",
    str_detect(descricao, "apensado") ~ "Apensado",
    str_detect(descricao, "digitacao de documentos") ~ "Digitação de documentos",
    str_detect(descricao, "baixa") ~ "Baixa",
    str_detect(descricao, "transito em julgado") ~ "Transitado em Julgado",
    str_detect(descricao, "decurso de prazo") ~ "Decurso de Prazo",
    str_detect(descricao, "emitido|movimentacao cartoraria tipo expedir mandado|expedicao|expedido") & str_detect(descricao, "mandado") ~ "Mandado Expedido",
    str_detect(descricao, "expedicao|expedido|emitido") & str_detect(descricao, "oficio") ~ "Ofício Expedido",
    str_detect(descricao, "expedicao|expedido") & str_detect(descricao, "carta") & str_detect(descricao, "precatoria") ~ "Carta precatória expedida",
    str_detect(descricao, "recebido") & str_detect(descricao, "carta") & str_detect(descricao, "precatoria") ~ "Carta precatória recebida",
    str_detect(descricao, "alvara") ~ "Alvara de soltura",
    str_detect(descricao, "certidao") ~ "Certidão",
    str_detect(descricao, "carta") ~ "Carta",
    str_detect(descricao, "guia recolhimento") ~ "Guia de recolhimento",
    str_detect(descricao, "termo de comparecimento") ~ "Termo de comparecimento",
    str_detect(descricao, "suspensao") ~ "Suspensão/Sobrestamento",
    str_detect(descricao, "requisicao") ~ "Requisição de honorários",
    str_detect(descricao, "edital") ~ "Edital",
    str_detect(descricao, "termo de fianca") ~ "Fiança",
    str_detect(descricao, "compromisso") ~ "Termo de compromisso",
    str_detect(descricao, "rol de culpados") ~ "Registro no rol de culpados",
    str_detect(descricao, "citacao") ~ "Citação",
    str_detect(descricao, "mandado(/oficio)?") & str_detect(descricao, "cumprido|positiv[ao]")  ~ "Mandado/Ofício Cumprido",
    str_detect(descricao, "mandado(/oficio)?") & str_detect(descricao, "não cumprido|negativ[ao]") ~ "Mandado/Ofício não cumprido",
    str_detect(descricao, "mandado/oficio remetido") ~ "Mandado/Ofício Remetido",
    str_detect(descricao, "cancelamento de mov") ~ "Cancelamento Movimentação",
    str_detect(descricao, "reativacao da mov") ~ "Reativação Movimentação",
    str_detect(descricao, "juntad") ~ "Juntado",
    str_detect(descricao, "serventuario") ~ "Serventuário",
    str_detect(descricao, "mero expediente") ~ "Mero expediente",
    str_detect(descricao, "aguardando") ~ "Aguardando",
    str_detect(descricao, "outros") ~ "Outros",
    str_detect(descricao, "mudanca de classe") ~ "Mudança de classe",
    str_detect(descricao, "guia de recolhimento") ~ "Guia de recolhimento",
    str_detect(descricao, "guia eletronica") ~ "Guia eletrônica",
    str_detect(descricao, "inquerito arquivado") ~ "Inquérito arquivado",
    str_detect(descricao, "processo de execucao da pena") ~ "Processo de execução de pena",
    str_detect(descricao, "processo desmembrado") ~ "Processo desmembrado",
    str_detect(descricao, "autos no prazo") ~ "Autos no prazo",
    str_detect(descricao, "distribuido|distribuicao") ~ "Distribuição",
    str_detect(descricao, "public|disponibiliz") ~ "Publicação",
    str_detect(descricao, "incidente processual") ~ "Incidente processual",
    str_detect(descricao, "expedicao de documento") ~ "Expedição de documento",
    str_detect(descricao, "concedida a dilacao") ~ "Concedida a dilação",
    str_detect(descricao, "processo desarquivado") ~ "Processo desarquivado",
    str_detect(descricao, "termo expedido") ~ "Termo expedido",
    str_detect(descricao, "enviado") ~ "Enviado",
    str_detect(descricao, "denuncia oferecida") ~ "Denúncia Oferecida",
    str_detect(descricao, "deliberacao") ~ "Deliberação",
    TRUE ~ descricao
  )
}

classifica_agente <- function(descricao, tipo_movimentacao){
  agente_sin <- case_when(
    str_detect(descricao, "mpf|ministerio publico|(^| )m\\.?p\\.?($| )") ~ "MP",
    str_detect(descricao, "policia") ~ "P",
    str_detect(descricao, "juiz") ~ "J1",
    str_detect(descricao, "desembargador|tribunal de justiça|tribunal regional|trf") ~ "J2"
  )
  
  case_when(
    str_detect(tipo_movimentacao, "Remessa|Carga") & is.na(agente_sin) ~ "Réu",
    TRUE ~ agente_sin
  )
}
